### PR TITLE
Update TeacherModel.cs

### PR DESCRIPTION
**Pull request by KATHIRVELSIVA**
Hi Priya, Good Morning
Could you please review my code.

### CODE REVIEW

**Review by Priyadharshini-B-23 — APPROVED** [review]
Hi Kathir Have a pleasant morning.
You  are doing a great job and your code is good.
However there is an error in  line 7 at TeacherModel.cs in Models folder.
Kindly could you please recheck it?

**Comment by KATHIRVELSIVA** [comment]
Thanks Priya for notifying the bug could you please recheck once again

**Review by Priyadharshini-B-23 — APPROVED** [review]
Yeah Kathir ,you did a good job the bug get resolved.
And there is also an error in line 25 at Program.cs file.
Could you please recheck it?

**Comment by KATHIRVELSIVA** [comment]
Hi Priya thanks for notifying the error in Program.cs file I have resolved the error 
Could you please check it once again.

**Review by Priyadharshini-B-23 — APPROVED** [review]
Excellent Kathir,you resolved all the bugs.
Your project is completely ready for the deployment process.

**Pull request merged**
